---
- name: Be sure vars for small is available
  include_tasks: import_vars/small.yml

- name: include_vars - medium
  include_vars:
    dir: medium

- name: Be sure vars for medium merged with vars for small
  set_fact:
    homebrew:
      packages: "{{ homebrew.packages + medium_packages }}"
      casks: "{{ homebrew.casks + medium_casks }}"
    apps: "{{ apps + medium_apps }}"
