homebrew:
  repos:
    official: 'homebrew/core,homebrew/services,homebrew/cask,homebrew/cask-fonts,homebrew/cask-drivers,wess/repo'
    homemade:
      - name: 'd-salt/homebrew'
        url: 'https://github.com/d-salt/homebrew-mycasks'

  packages:
    - cmake
    - curl
    - coreutils
    - emacs
    - findutils
    - gcc
    - git
    - grep
    - mas
    - mackup
    - nmap
    - gnu-sed
    - source-highlight
    - tidy-html5
    - tmux
    - tree
    - wget
    - zsh
    - zsh-completions

  casks:
    - alfred
    - clipy
    - docker
    - firefox
    - google-analytics-opt-out
    - google-chrome
    - google-japanese-ime
    - gyazo
    - iterm2
    - font-myrica
    - font-fira-code
    - font-source-han-sans
    - font-source-han-serif
    - visual-studio-code
    - appcleaner
    - slack

apps:
  - name: 1Password 7
    id: "1333542190"
  - name: CotEditor
    id: "1024640650"
  - name: Magnet
    id: "441258766"
  - name: The Unarchiver
    id: "425424353"
  - name: WinArchiver Lite
    id: "414855915"
  - name: Amphetamine
    id: "937984704"
  - name: Focus
    id: "777233759"
  - name: Instapaper
    id: "1481302432"
    id: "1055511498"
  - name: OneLogin for Safari
    id: "1475824389"
  # - name: Xcode
  #   id: 497799835
